steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: "gcr.io/$PROJECT_ID/sonar-scanner:latest" 
    args: [ 
      "-Dsonar.projectKey=sonar-jenkins", 
      "-Dsonar.sources=./src", 
      "-Dsonar.host.url=http://34.93.141.200:9000", 
      "-Dsonar.login=${_SONAR_TOKEN}",
      "-Dsonar.java.binaries=.",
      "-Dsonar.qualitygate.wait=true" ]
substitutions:
  _SONAR_TOKEN: "6d6599c9efa9a9e013bd29c1ea98bfaa27b08f5a"
