steps:
 - name: 'gcr.io/cloud-builders/mvn'
   args: ['install','clean']
   
 - name: ‘Google Cloud Platform’
   env:
    ‘SONAR_HOST_URL=admin’
    ‘SONAR_LOGIN=admin’
    args:
      ‘mvn clean verify sonar:sonar’
      ‘-Dsonar.projectKey=’
      ‘-Dsonar.sources=.’
      ‘-Dsonar.qualitygate.wait=true allow_failure: true’
      id: sonarqube
      entrypoint: sh
