steps:
  #static code analysis by sonarqube
  - name: 'maven:3.6.8-jdk-8'
    entrypoint: 'bash'
    args:
     - -c
     - |
        mvn sonar:sonar -q -Dsonar.login=e0a95d4b25ed8ad54f8906bc5e0f6e486b7fbeb2 \
        '-Dsonar.projectKey=e0a95d4b25ed8ad54f8906bc5e0f6e486b7fbeb2' \
        '-Dsonar.projectName=springboot' \
        '-Dsonar.host.url=https://34.100.139.97:9000' \
        '-Dsonar.qualitygate.wait=true' \
        'allow_failure: true'
    id: 'sonarqube-analysis'
